[project]
name = "sft-instant-scanner"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.nft-scanner-core]
path = "contracts/nft-scanner-core.clar"
depends_on = []

[contracts.nft-scanner-licensing]
path = "contracts/nft-scanner-licensing.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
